### ISSUE TITLE
Python exception: No module named pygments.lexers

### ISSUE THREAD

**Issue by apple-avadhesh** [sowenjub/CasperishTheme#3]
`publish run` throws error : Fatal error: 'try!' expression unexpectedly raised an error: Python exception: No module named pygments.lexers

Comment out : `plugins: [.pygments()]` worked though.

**Comment by sowenjub** [comment]
Sorry I stopped using Publish because it wasn't really active. The pygments plugin was added to get syntax highlighting, so you can probably do without it.

**Comment by apple-avadhesh** [comment]
Thanks for the update. Without `pygments` it's working for now.
